_target_: src.models.components.global_net.RegressionHead
emb_dim: ${local_emb_dim}                # Embedding dimension of local metric
aggregation: delta                       # [concat, delta, relative] aggregation type
add_norm: false                          # Whether to add norm for input of model or not
out_activation: elu                      # Activation at the output [elu]
activation: ${model.net.activation}      # Activation function
p_dropout: ${model.net.p_dropout}        # Dropout probability
