defaults:
  - base
  - net: habitat                                 # Pick whichever model you want here [jackal, maze]
  - net@inverse_kinematics: inverse_kinematics    # Pick whichever model you want here [jackal, maze]
  - loss: ce_none                                # Pick loss here [infonce, hinge]
  - loss@val_loss: null                          # Pick loss here [infonce, hinge] Null will use the same as train

_target_: src.models.local_backbone.LocalBackbone
n_edges: 10000             # Number of edges randomly sampled to plot connectivity graph
n_samples: 5               # Number of false positives edges used to plot
rho: 4                     # Threshold to visualize far spurious connections
step_every: 1