_target_: src.models.loss.CEConnectivity
alpha: 1.0           # Weighting term of contrastive loss
contrastive_loss:
  _target_: src.models.loss.HingeLoss
  pos_d: 1.0           # Distance between positives
  neg_d: 2.0           # Distance between negatives
  tau: 1.0
  loss: 'huber'        # Options are [l1, l2, huber]
  scale: 1.0           # Scaling factor for distances in loss
  # speed_target and margin are not used by standard formulation
  hinge_loss: true