_target_: src.models.loss.HingeLoss
pos_d: 1.0           # Distance between positives
neg_d: 2.0           # Distance between negatives
tau: 1.0
scale: 1.0           # Scale for distances
loss: 'huber'        # Options are [l1, l2, huber]
hinge_loss: true     # Whether hinge negative part of the loss or not